// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package protos // import "github.com/go-ignite/ignite-agent/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceType_Enum int32

const (
	ServiceType_NOT_SET  ServiceType_Enum = 0
	ServiceType_SS_LIBEV ServiceType_Enum = 1
	ServiceType_SSR      ServiceType_Enum = 2
)

var ServiceType_Enum_name = map[int32]string{
	0: "NOT_SET",
	1: "SS_LIBEV",
	2: "SSR",
}
var ServiceType_Enum_value = map[string]int32{
	"NOT_SET":  0,
	"SS_LIBEV": 1,
	"SSR":      2,
}

func (x ServiceType_Enum) String() string {
	return proto.EnumName(ServiceType_Enum_name, int32(x))
}
func (ServiceType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{0, 0}
}

type ServiceType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceType) Reset()         { *m = ServiceType{} }
func (m *ServiceType) String() string { return proto.CompactTextString(m) }
func (*ServiceType) ProtoMessage()    {}
func (*ServiceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{0}
}
func (m *ServiceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceType.Unmarshal(m, b)
}
func (m *ServiceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceType.Marshal(b, m, deterministic)
}
func (dst *ServiceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceType.Merge(dst, src)
}
func (m *ServiceType) XXX_Size() int {
	return xxx_messageInfo_ServiceType.Size(m)
}
func (m *ServiceType) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceType.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceType proto.InternalMessageInfo

type GeneralRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{1}
}
func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (dst *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(dst, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GeneralResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{2}
}
func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (dst *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(dst, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

type HeartbeatStreamServer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatStreamServer) Reset()         { *m = HeartbeatStreamServer{} }
func (m *HeartbeatStreamServer) String() string { return proto.CompactTextString(m) }
func (*HeartbeatStreamServer) ProtoMessage()    {}
func (*HeartbeatStreamServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{3}
}
func (m *HeartbeatStreamServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatStreamServer.Unmarshal(m, b)
}
func (m *HeartbeatStreamServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatStreamServer.Marshal(b, m, deterministic)
}
func (dst *HeartbeatStreamServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatStreamServer.Merge(dst, src)
}
func (m *HeartbeatStreamServer) XXX_Size() int {
	return xxx_messageInfo_HeartbeatStreamServer.Size(m)
}
func (m *HeartbeatStreamServer) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatStreamServer.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatStreamServer proto.InternalMessageInfo

type GetAvailablePortRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UsedPorts            []int32  `protobuf:"varint,2,rep,packed,name=used_ports,json=usedPorts,proto3" json:"used_ports,omitempty"`
	PortFrom             int32    `protobuf:"varint,3,opt,name=port_from,json=portFrom,proto3" json:"port_from,omitempty"`
	PortTo               int32    `protobuf:"varint,4,opt,name=port_to,json=portTo,proto3" json:"port_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvailablePortRequest) Reset()         { *m = GetAvailablePortRequest{} }
func (m *GetAvailablePortRequest) String() string { return proto.CompactTextString(m) }
func (*GetAvailablePortRequest) ProtoMessage()    {}
func (*GetAvailablePortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{4}
}
func (m *GetAvailablePortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvailablePortRequest.Unmarshal(m, b)
}
func (m *GetAvailablePortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvailablePortRequest.Marshal(b, m, deterministic)
}
func (dst *GetAvailablePortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailablePortRequest.Merge(dst, src)
}
func (m *GetAvailablePortRequest) XXX_Size() int {
	return xxx_messageInfo_GetAvailablePortRequest.Size(m)
}
func (m *GetAvailablePortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailablePortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailablePortRequest proto.InternalMessageInfo

func (m *GetAvailablePortRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetAvailablePortRequest) GetUsedPorts() []int32 {
	if m != nil {
		return m.UsedPorts
	}
	return nil
}

func (m *GetAvailablePortRequest) GetPortFrom() int32 {
	if m != nil {
		return m.PortFrom
	}
	return 0
}

func (m *GetAvailablePortRequest) GetPortTo() int32 {
	if m != nil {
		return m.PortTo
	}
	return 0
}

type GetAvailablePortResponse struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvailablePortResponse) Reset()         { *m = GetAvailablePortResponse{} }
func (m *GetAvailablePortResponse) String() string { return proto.CompactTextString(m) }
func (*GetAvailablePortResponse) ProtoMessage()    {}
func (*GetAvailablePortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{5}
}
func (m *GetAvailablePortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvailablePortResponse.Unmarshal(m, b)
}
func (m *GetAvailablePortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvailablePortResponse.Marshal(b, m, deterministic)
}
func (dst *GetAvailablePortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailablePortResponse.Merge(dst, src)
}
func (m *GetAvailablePortResponse) XXX_Size() int {
	return xxx_messageInfo_GetAvailablePortResponse.Size(m)
}
func (m *GetAvailablePortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailablePortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailablePortResponse proto.InternalMessageInfo

func (m *GetAvailablePortResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type CreateServiceRequest struct {
	Token                string           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Port                 int32            `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type                 ServiceType_Enum `protobuf:"varint,3,opt,name=type,proto3,enum=ServiceType_Enum" json:"type,omitempty"`
	Method               string           `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Password             string           `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string           `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{6}
}
func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(dst, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateServiceRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CreateServiceRequest) GetType() ServiceType_Enum {
	if m != nil {
		return m.Type
	}
	return ServiceType_NOT_SET
}

func (m *CreateServiceRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CreateServiceRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StopServiceRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServiceRequest) Reset()         { *m = StopServiceRequest{} }
func (m *StopServiceRequest) String() string { return proto.CompactTextString(m) }
func (*StopServiceRequest) ProtoMessage()    {}
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{7}
}
func (m *StopServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServiceRequest.Unmarshal(m, b)
}
func (m *StopServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServiceRequest.Marshal(b, m, deterministic)
}
func (dst *StopServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServiceRequest.Merge(dst, src)
}
func (m *StopServiceRequest) XXX_Size() int {
	return xxx_messageInfo_StopServiceRequest.Size(m)
}
func (m *StopServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServiceRequest proto.InternalMessageInfo

func (m *StopServiceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *StopServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type CreateServiceResponse struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_7bfa070e03e80e6c, []int{8}
}
func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (dst *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(dst, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

func (m *CreateServiceResponse) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceType)(nil), "ServiceType")
	proto.RegisterType((*GeneralRequest)(nil), "GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "GeneralResponse")
	proto.RegisterType((*HeartbeatStreamServer)(nil), "HeartbeatStreamServer")
	proto.RegisterType((*GetAvailablePortRequest)(nil), "GetAvailablePortRequest")
	proto.RegisterType((*GetAvailablePortResponse)(nil), "GetAvailablePortResponse")
	proto.RegisterType((*CreateServiceRequest)(nil), "CreateServiceRequest")
	proto.RegisterType((*StopServiceRequest)(nil), "StopServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "CreateServiceResponse")
	proto.RegisterEnum("ServiceType_Enum", ServiceType_Enum_name, ServiceType_Enum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	NodeHeartbeat(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (AgentService_NodeHeartbeatClient, error)
	ServiceHeartbeat(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (AgentService_ServiceHeartbeatClient, error)
	Init(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetAvailablePort(ctx context.Context, in *GetAvailablePortRequest, opts ...grpc.CallOption) (*GetAvailablePortResponse, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error)
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) NodeHeartbeat(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (AgentService_NodeHeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AgentService_serviceDesc.Streams[0], "/AgentService/NodeHeartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceNodeHeartbeatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_NodeHeartbeatClient interface {
	Recv() (*HeartbeatStreamServer, error)
	grpc.ClientStream
}

type agentServiceNodeHeartbeatClient struct {
	grpc.ClientStream
}

func (x *agentServiceNodeHeartbeatClient) Recv() (*HeartbeatStreamServer, error) {
	m := new(HeartbeatStreamServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ServiceHeartbeat(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (AgentService_ServiceHeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AgentService_serviceDesc.Streams[1], "/AgentService/ServiceHeartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceServiceHeartbeatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_ServiceHeartbeatClient interface {
	Recv() (*HeartbeatStreamServer, error)
	grpc.ClientStream
}

type agentServiceServiceHeartbeatClient struct {
	grpc.ClientStream
}

func (x *agentServiceServiceHeartbeatClient) Recv() (*HeartbeatStreamServer, error) {
	m := new(HeartbeatStreamServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) Init(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/AgentService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAvailablePort(ctx context.Context, in *GetAvailablePortRequest, opts ...grpc.CallOption) (*GetAvailablePortResponse, error) {
	out := new(GetAvailablePortResponse)
	err := c.cc.Invoke(ctx, "/AgentService/GetAvailablePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error) {
	out := new(CreateServiceResponse)
	err := c.cc.Invoke(ctx, "/AgentService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/AgentService/StopService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	NodeHeartbeat(*GeneralRequest, AgentService_NodeHeartbeatServer) error
	ServiceHeartbeat(*GeneralRequest, AgentService_ServiceHeartbeatServer) error
	Init(context.Context, *GeneralRequest) (*GeneralResponse, error)
	GetAvailablePort(context.Context, *GetAvailablePortRequest) (*GetAvailablePortResponse, error)
	CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error)
	StopService(context.Context, *StopServiceRequest) (*GeneralResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_NodeHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GeneralRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).NodeHeartbeat(m, &agentServiceNodeHeartbeatServer{stream})
}

type AgentService_NodeHeartbeatServer interface {
	Send(*HeartbeatStreamServer) error
	grpc.ServerStream
}

type agentServiceNodeHeartbeatServer struct {
	grpc.ServerStream
}

func (x *agentServiceNodeHeartbeatServer) Send(m *HeartbeatStreamServer) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_ServiceHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GeneralRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ServiceHeartbeat(m, &agentServiceServiceHeartbeatServer{stream})
}

type AgentService_ServiceHeartbeatServer interface {
	Send(*HeartbeatStreamServer) error
	grpc.ServerStream
}

type agentServiceServiceHeartbeatServer struct {
	grpc.ServerStream
}

func (x *agentServiceServiceHeartbeatServer) Send(m *HeartbeatStreamServer) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AgentService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Init(ctx, req.(*GeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAvailablePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailablePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAvailablePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AgentService/GetAvailablePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAvailablePort(ctx, req.(*GetAvailablePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AgentService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AgentService/StopService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _AgentService_Init_Handler,
		},
		{
			MethodName: "GetAvailablePort",
			Handler:    _AgentService_GetAvailablePort_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _AgentService_CreateService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _AgentService_StopService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NodeHeartbeat",
			Handler:       _AgentService_NodeHeartbeat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServiceHeartbeat",
			Handler:       _AgentService_ServiceHeartbeat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_7bfa070e03e80e6c) }

var fileDescriptor_agent_7bfa070e03e80e6c = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0xb9, 0x7b, 0xd2, 0x8b, 0x3b, 0x34, 0x89, 0x09, 0xaa, 0x14, 0x59, 0x02, 0x85, 0x4a,
	0xdd, 0xa0, 0x82, 0x90, 0x40, 0x02, 0xa9, 0x45, 0x21, 0x44, 0x42, 0x05, 0xd9, 0x11, 0x0f, 0xbc,
	0x58, 0x4e, 0x3d, 0xa4, 0x16, 0xb1, 0xd7, 0xac, 0x37, 0x45, 0x7d, 0xe7, 0x7f, 0xf8, 0x38, 0x7e,
	0x00, 0xed, 0xc6, 0x84, 0xe6, 0xd2, 0x0a, 0xf5, 0x69, 0x77, 0xe6, 0xcc, 0x19, 0x1f, 0xcf, 0x1c,
	0x2d, 0xd4, 0x83, 0x09, 0x25, 0x92, 0xa5, 0x82, 0x4b, 0xee, 0xbc, 0x84, 0xba, 0x47, 0xe2, 0x32,
	0x3a, 0xa7, 0xd1, 0x55, 0x4a, 0xce, 0x21, 0x94, 0xfa, 0xc9, 0x2c, 0xc6, 0x3a, 0x54, 0xcf, 0x3e,
	0x8e, 0x7c, 0xaf, 0x3f, 0xb2, 0xee, 0xe1, 0x16, 0xd4, 0x3c, 0xcf, 0xff, 0x30, 0x3c, 0xed, 0x7f,
	0xb6, 0x0c, 0xac, 0x42, 0xd1, 0xf3, 0x5c, 0xab, 0xe0, 0x3c, 0x86, 0x9d, 0x01, 0x25, 0x24, 0x82,
	0xa9, 0x4b, 0xdf, 0x67, 0x94, 0x49, 0xdc, 0x87, 0xb2, 0xe4, 0xdf, 0x28, 0xb1, 0x8d, 0x8e, 0xd1,
	0x35, 0xdd, 0x79, 0xe0, 0xec, 0xc1, 0xee, 0xa2, 0x2e, 0x4b, 0x79, 0x92, 0x91, 0xd3, 0x82, 0xc6,
	0x7b, 0x0a, 0x84, 0x1c, 0x53, 0x20, 0x3d, 0x29, 0x28, 0x88, 0x95, 0x08, 0x12, 0xce, 0x4f, 0x03,
	0x5a, 0x03, 0x92, 0x27, 0x97, 0x41, 0x34, 0x0d, 0xc6, 0x53, 0xfa, 0xc4, 0x85, 0xbc, 0xb5, 0x3b,
	0x1e, 0x00, 0xcc, 0x32, 0x0a, 0xfd, 0x94, 0x0b, 0x99, 0xd9, 0x85, 0x4e, 0xb1, 0x5b, 0x76, 0x4d,
	0x95, 0x51, 0xd4, 0x0c, 0x1f, 0x82, 0xa9, 0x10, 0xff, 0xab, 0xe0, 0xb1, 0x5d, 0xec, 0x18, 0xdd,
	0xb2, 0x5b, 0x53, 0x89, 0x77, 0x82, 0xc7, 0xd8, 0x82, 0xaa, 0x06, 0x25, 0xb7, 0x4b, 0x1a, 0xaa,
	0xa8, 0x70, 0xc4, 0x1d, 0x06, 0xf6, 0xba, 0x8a, 0xb9, 0x76, 0x44, 0x28, 0xa9, 0x2a, 0xad, 0xa2,
	0xec, 0xea, 0xbb, 0xf3, 0xcb, 0x80, 0xfd, 0xb7, 0x82, 0x02, 0x49, 0xf9, 0x30, 0x6f, 0xd7, 0xfc,
	0xb7, 0x45, 0xe1, 0x5f, 0x0b, 0x7c, 0x04, 0x25, 0x79, 0x95, 0x92, 0xd6, 0xb8, 0x73, 0xbc, 0xc7,
	0xae, 0x6d, 0x85, 0xa9, 0x95, 0xb8, 0x1a, 0xc6, 0x26, 0x54, 0x62, 0x92, 0x17, 0x3c, 0xd4, 0x8a,
	0x4d, 0x37, 0x8f, 0xb0, 0x0d, 0xb5, 0x34, 0xc8, 0xb2, 0x1f, 0x5c, 0x84, 0x76, 0x59, 0x23, 0x8b,
	0x58, 0x7d, 0x2e, 0x09, 0x62, 0xb2, 0x2b, 0x3a, 0xaf, 0xef, 0xce, 0x10, 0xd0, 0x93, 0x3c, 0xfd,
	0x2f, 0xb9, 0x07, 0x00, 0xd9, 0xbc, 0xce, 0x8f, 0x42, 0x2d, 0xda, 0x74, 0xcd, 0x3c, 0x33, 0x0c,
	0x9d, 0x17, 0xd0, 0x58, 0xf9, 0xf7, 0x7c, 0x52, 0xcb, 0x3c, 0x63, 0x85, 0x77, 0xfc, 0xbb, 0x00,
	0x5b, 0x27, 0xca, 0x8a, 0x39, 0x0f, 0x5f, 0xc1, 0xf6, 0x19, 0x0f, 0x69, 0xe1, 0x0c, 0xdc, 0x65,
	0xcb, 0x06, 0x6b, 0x37, 0xd9, 0x46, 0xdb, 0x3c, 0x35, 0xf0, 0x35, 0x58, 0x79, 0x9b, 0x3b, 0xd1,
	0x9f, 0x40, 0x69, 0x98, 0x44, 0x1b, 0x28, 0x16, 0x5b, 0xf1, 0x2e, 0x0e, 0xc0, 0x5a, 0xf5, 0x06,
	0xda, 0xec, 0x06, 0xd3, 0xb6, 0x1f, 0xb0, 0x1b, 0x8d, 0xf4, 0x06, 0xb6, 0x97, 0xe6, 0x86, 0x0d,
	0xb6, 0xc9, 0x43, 0xed, 0x26, 0xdb, 0x3c, 0xde, 0xe7, 0x50, 0xbf, 0xb6, 0x42, 0xbc, 0xcf, 0xd6,
	0x17, 0xba, 0x2e, 0xff, 0xf4, 0xf0, 0x4b, 0x77, 0x12, 0xc9, 0x8b, 0xd9, 0x98, 0x9d, 0xf3, 0xb8,
	0x37, 0xe1, 0x47, 0xd1, 0x24, 0x89, 0x24, 0xf5, 0xe6, 0xc7, 0x91, 0x7e, 0x1b, 0x7a, 0xfa, 0x6d,
	0xc8, 0xc6, 0x15, 0x7d, 0x3e, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x31, 0x6f, 0x6c, 0x02, 0x32,
	0x04, 0x00, 0x00,
}
